[project]
name = "jac-gpt-"
version = "1.0.0"
description = "Jac application: jac-coding-assistant"
entry-point = "server.jac"

[plugins.scale.kubernetes]
app_name = "jac-gpt-test"
namespace = "jac-gpt-test"

[dependencies]
python-dotenv = ">=0.0.0"
requests = ">=0.0.0"
byllm = ">=0.0.0"
pymongo = ">=0.0.0"
langchain-openai = ">=0.0.0"
langchain-community = ">=0.0.0"
langchain-chroma = ">=0.0.0"
pypdf = ">=0.0.0"
sentence-transformers = ">=0.0.0"
faiss-cpu = ">=0.0.0"
