[project]
name = "learning-companion"
version = "1.0.0"
description = "Jac client application: learning-companion"
entry-point = "src/app.jac"

[plugins.client]

[dependencies.npm]
"@mui/material" = "7.3.5"
"@mui/icons-material" = "7.3.5"
"@mui/lab" = "7.0.1-beta.19"
"@emotion/react" = "11.14.0"
"@emotion/styled" = "11.14.1"
framer-motion = "12.23.24"
